#!/usr/bin/sh

echo 'next: disable bluealsa.service';
systemctl stop bluealsa-aplay 2>&1
systemctl disable bluealsa-aplay 2>&1
systemctl stop bluealsa.service 2>&1
systemctl disable bluealsa.service 2>&1
echo 'next: done';
