#!/usr/bin/bash


MEDIACENTER="/usr/bin/mediacenter"
MEDIACENTERBK="/usr/bin/mediacenter.backup"


if  grep -q "Open Source Media Center" "/etc/os-release" ; then
	echo 'next: update apt source'; 
	apt update
	echo 'next: upgrade system'; 
	apt upgrade -y

	echo 'next: install pulseaudio'; 
	apt install -y pulseaudio
	echo 'next: install pulseaudio-equalizer'; 
	apt install -y pulseaudio-equalizer swh-plugins
	echo 'next: install pulseaudio-module-bluetooth'; 
	apt install -y pulseaudio-module-bluetooth
	
	usermod -a -G pulse $USER
	
	su -u osmc systemctl --user start pulseaudio.service 2>&1
	
	if [ ! -f "/home/osmc/.config/pulse" ]; then
		sudo -u osmc mkdir -p /home/osmc/.config/pulse
	fi	
	
	if [ ! -f "/home/osmc/.config/pulse/default.pa" ]; then
		sudo -u osmc cp /etc/pulse/default.pa /home/osmc/.config/pulse/
		sudo -u osmc sed -i "s/load-module module-udev-detect/load-module module-udev-detect tsched=no/g" "/home/osmc/.config/pulse/default.pa"
		sudo -u osmc echo -e 'load-module module-ladspa-sink sink_name=co-1 sink_properties="device.description=compressor" plugin=sc4_1882 label=sc4 control=1,1.5,401,-20,20,5,15' >>  /home/osmc/.config/pulse/default.pa
		sudo -u osmc echo -e 'load-module module-equalizer-sink sink_master=co-1 sink_name=eq-1 sink_properties="device.description=equalizer & compressor"' >>  /home/osmc/.config/pulse/default.pa
	fi
	
	if [ ! -f "/home/osmc/.config/pulse/daemon.conf" ]; then
		sudo -u osmc cp /etc/pulse/daemon.conf  /home/osmc/.config/pulse/
		sudo -u osmc echo -e 'default-fragments = 8' >> /home/osmc/.config/pulse/daemon.conf
		sudo -u osmc echo -e 'default-fragment-size-msec = 20' >> /home/osmc/.config/pulse/daemon.conf
	fi
	
	
	echo 'next: change OSMC start script'; 
	
	if [ ! -f $MEDIACENTERBK ]; then
		cp $MEDIACENTER $MEDIACENTERBK
	fi

	if  grep -q "su osmc " $MEDIACENTER ; then
		echo '/usr/bin/mediacenter is already updated'; 
	else
		if  grep -q "sudo -u osmc LIRC_SOCKET_PATH" $MEDIACENTER ; then
			sed -i "s/sudo -u osmc /su osmc -c \"LIRC_SOCKET_PATH=\/var\/run\/lirc\/lircd XDG_RUNTIME_DIR=\/run\/user\/$(id -u osmc) \$KODI --standalone -fs;  CODE=\$?\"\n\t#sudo -u osmc /g" $MEDIACENTER
		else
			echo 'error: /usr/bin/mediacenter has changed, cannot update';
		fi
	fi
	
	if [ ! -f "/home/osmc/.kodi/temp/repository.linuxaddons-1.0.0.zip" ]; then
		echo 'next: download Linux Addon Repository';
		sudo -u osmc wget -q https://raw.github.com/wastis/LinuxAddonRepo/master/repository.linuxaddons-1.0.0.zip -P /home/osmc/.kodi/temp/
	fi
	echo 'next: install Linux Addon Repository';
	sudo -u osmc unzip -o -d /home/osmc/.kodi/addons /home/osmc/.kodi/temp/repository.linuxaddons-1.0.0.zip
	
	echo 'next: recompile python libararies for performance reason'
	python -m compileall -o 1 /usr/lib/python3*

else
	echo 'ERROR: This script is targeted for osmc installations.';
fi

echo '\n--- done ---\n'; 
