#!/usr/bin/bash


echo 'next: restore pulseaudio default setting';
 
sudo -u osmc cp /etc/pulse/default.pa /home/osmc/.config/pulse/
sudo -u osmc sed -i "s/load-module module-udev-detect/load-module module-udev-detect tsched=no/g" "/home/osmc/.config/pulse/default.pa"
sudo -u osmc echo -e 'load-module module-ladspa-sink sink_name=co-1 sink_properties="device.description=compressor" plugin=sc4_1882 label=sc4 control=1,1.5,401,-20,20,5,15' >>  /home/osmc/.config/pulse/default.pa
sudo -u osmc echo -e 'load-module module-equalizer-sink sink_master=co-1 sink_name=eq-1 sink_properties="device.description=equalizer & compressor"' >>  /home/osmc/.config/pulse/default.pa
sudo -u osmc cp /etc/pulse/daemon.conf  /home/osmc/.config/pulse/
sudo -u osmc echo -e 'default-fragments = 8' >> /home/osmc/.config/pulse/daemon.conf
sudo -u osmc echo -e 'default-fragment-size-msec = 20' >> /home/osmc/.config/pulse/daemon.conf

echo 'next: done';
